### ISSUE TITLE
mail_relay.server is required

### ISSUE THREAD

**Issue by muzicaed** [systemconsole/syco#171]
When installing syco just for development, I was forced to define mail_relay.server in the install.cfg.
I found no way of setting the mail_relay.server property to null, blank or what ever, and instead needed to add this to get it to install:

mail_relay.domain_name: localhost
mail_relay.server: mailrelay_dummy

[mailrelay_dummy]
type: host
front.ip: 192.168.0.1
back.ip: 192.168.0.1

**Comment by kribor** [comment]
The config that's in the general-of file should work. That doesnt actually define the host but refers it to non-syco host:
mailrelay.domain_name: <ip>
mailrelay.server: mail
mailrelay.server.ip: <ip>

**Comment by kribor** [comment]
Which service were you installing when it crashed BTW? mailrelay or another service?

**Comment by muzicaed** [comment]
Im not sure, it might just be me operating it wrong.
I'll see if I can get some time to re-do the stuff and figure out if there is an issue or just me. :)
